### ISSUE TITLE
unexistant dependency "bin-build"

### ISSUE THREAD

**Issue by xodock** [pid/speakingurl#106]
```
Error: Cannot find module 'bin-build'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/node_modules/pngquant-bin/lib/install.js:2:16)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

**Comment by pid** [comment]
could not reproduce, please more details
thanks

**Comment by simison** [comment]
@xodock you're at wrong repo.

You're missing this:
https://github.com/papandreou/node-pngquant/blob/master/package.json#L9-L11

From this package:
https://github.com/papandreou/node-pngquant
